name: hrm
description: "A new Flutter project."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^14.8.0
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  provider: ^6.1.0
  share_plus: ^10.1.0
  shared_preferences: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  freezed: ^3.0.0
  json_serializable: ^6.9.0
  go_router_builder: ^2.8.0
  flutter_gen_runner: ^5.9.0
  flutter_launcher_icons: ^0.14.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/jsons/

flutter_gen:
  output: lib/config
  integrations:
    image: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
  colors:
    enabled: true
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml
